#!/bin/sh
':' //; exec "$(command -v nodejs || command -v node)" "$0" "$@"

var formats = require("./formats.js");
var adjectives = require("./adjectives.js");
var subjects = require("./subjects.js");
var utils = require("./utils.js");

var componentGenerators = {
	adj: function adjective() { return utils.randomchoose(adjectives) },
	sub: function subject() { return utils.randomchoose(subjects) },
};

// First, checks if it isn't implemented yet.
if (!String.prototype.format) {
  String.prototype.format = function() {
    return this.replace(/{(\w+)}/g, function(match, type) { 

      return typeof componentGenerators[type] != 'undefined'
        ? componentGenerators[type]()
        : match
      ;
    });
  };
}

console.log(
	utils.randomchoose(formats).format(
		utils.randomchoose(adjectives), 
		utils.randomchoose(subjects)
	)
);
